# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: Deploy lighthouse results to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the lighthouse results'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    container:
      image: justinribeiro/lighthouse
      options: --cap-add=SYS_ADMIN --user root
      volumes:
        - ${{ github.workspace }}/lighthouse-result/:/home/chrome/reports
      env:
        LIGHTHOUSE_URL: ${{ inputs.url }}

    steps:
      - run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - run: echo "URL=$(echo ${{ inputs.url }} | sed -E 's/^https?:\/\///' | cut -d'/' -f1)" >> $GITHUB_ENV

      - name: Execute lighthouse
        run: |
          echo y | /usr/bin/lighthouse --output-path=/home/chrome/reports/${{ env.URL }}_${{ env.NOW }}.html --chrome-flags="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage" ${{ inputs.url }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ github.workspace }}/lighthouse-result"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4